### ISSUE TITLE
Cannot get this working as an Azure Function

### ISSUE THREAD

**Issue by itsandreramon** [jdubois/spring-reactive-sql-server#1]
I have a similiar project that uses Azure Functions. Deploying the project locally using a normal Controller to access the database works, but when packaged as a Azure Function (using Azure Gradle plugin) gives me the following error:

```
[2021-03-12T12:33:34.934Z] ***************************
[2021-03-12T12:33:34.934Z] APPLICATION FAILED TO START
[2021-03-12T12:33:34.934Z] ***************************
[2021-03-12T12:33:34.934Z] Description:
[2021-03-12T12:33:34.934Z] Failed to configure a ConnectionFactory: 'url' attribute is not specified and no embedded database could be configured.
[2021-03-12T12:33:34.934Z] Reason: Failed to determine a suitable R2DBC Connection URL
[2021-03-12T12:33:34.934Z] Action:
[2021-03-12T12:33:34.934Z] Consider the following:
[2021-03-12T12:33:34.934Z] 	If you want an embedded database (H2), please put it on the classpath.
[2021-03-12T12:33:34.934Z] 	If you have database settings to be loaded from a particular profile you may need to activate it (no profiles are currently active).
[2021-03-12T12:33:35.033Z] Executed 'Functions.hello' (Failed, Id=76e2d158-a4a2-4e7e-b652-22c44fb48b88, Duration=2400ms)
[2021-03-12T12:33:35.033Z] System.Private.CoreLib: Exception while executing function: Functions.hello. System.Private.CoreLib: Result: Failure
[2021-03-12T12:33:35.033Z] Exception: ConnectionFactoryBuilder.ConnectionFactoryBeanCreationException: Failed to determine a suitable R2DBC Connection URL
[2021-03-12T12:33:35.033Z] Stack: java.lang.reflect.InvocationTargetException
[2021-03-12T12:33:35.033Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2021-03-12T12:33:35.033Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2021-03-12T12:33:35.033Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2021-03-12T12:33:35.033Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2021-03-12T12:33:35.033Z] 	at com.microsoft.azure.functions.worker.broker.JavaMethodInvokeInfo.invoke(JavaMethodInvokeInfo.java:22)
[2021-03-12T12:33:35.033Z] 	at com.microsoft.azure.functions.worker.broker.EnhancedJavaMethodExecutorImpl.execute(EnhancedJavaMethodExecutorImpl.java:55)
[2021-03-12T12:33:35.033Z] 	at com.microsoft.azure.functions.worker.broker.JavaFunctionBroker.invokeMethod(JavaFunctionBroker.java:57)
[2021-03-12T12:33:35.033Z] 	at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:33)
[2021-03-12T12:33:35.033Z] 	at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:10)
[2021-03-12T12:33:35.033Z] 	at com.microsoft.azure.functions.worker.handler.MessageHandler.handle(MessageHandler.java:45)
[2021-03-12T12:33:35.033Z] 	at com.microsoft.azure.functions.worker.JavaWorkerClient$StreamingMessagePeer.lambda$onNext$0(JavaWorkerClient.java:92)
[2021-03-12T12:33:35.033Z] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[2021-03-12T12:33:35.033Z] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[2021-03-12T12:33:35.033Z] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2021-03-12T12:33:35.033Z] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2021-03-12T12:33:35.033Z] 	at java.base/java.lang.Thread.run(Thread.java:834)
[2021-03-12T12:33:35.033Z] Caused by: java.lang.RuntimeException: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'connectionFactory' defined in class path resource [org/springframework/boot/autoconfigure/r2dbc/ConnectionFactoryConfigurations$Pool.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [io.r2dbc.pool.ConnectionPool]: Factory method 'connectionFactory' threw exception; nested exception is org.springframework.boot.autoconfigure.r2dbc.ConnectionFactoryBuilder$ConnectionFactoryBeanCreationException: Failed to determine a suitable R2DBC Connection URL
[2021-03-12T12:33:35.033Z] 	at org.springframework.cloud.function.adapter.azure.AzureSpringBootRequestHandler.handleRequest(AzureSpringBootRequestHandler.java:101)
[2021-03-12T12:33:35.033Z] 	at com.example.HelloHandler.execute(HelloHandler.java:33)
[2021-03-12T12:33:35.033Z] 	... 16 more
[2021-03-12T12:33:35.033Z] Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'connectionFactory' defined in class path resource [org/springframework/boot/autoconfigure/r2dbc/ConnectionFactoryConfigurations$Pool.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [io.r2dbc.pool.ConnectionPool]: Factory method 'connectionFactory' threw exception; nested exception is org.springframework.boot.autoconfigure.r2dbc.ConnectionFactoryBuilder$ConnectionFactoryBeanCreationException: Failed to determine a suitable R2DBC Connection URL
[2021-03-12T12:33:35.033Z] 	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:658)
[2021-03-12T12:33:35.033Z] 	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:638)
[2021-03-12T12:33:35.033Z] 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1334)
[2021-03-12T12:33:35.033Z] 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1177)
[2021-03-12T12:33:35.033Z] 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:564)
[2021-03-12T12:33:35.033Z] 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:524)
[2021-03-12T12:33:35.033Z] 	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
[2021-03-12T12:33:35.033Z] 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
[2021-03-12T12:33:35.033Z] 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
[2021-03-12T12:33:35.033Z] 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
[2021-03-12T12:33:35.033Z] 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:944)
[2021-03-12T12:33:35.033Z] 	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:917)
[2021-03-12T12:33:35.033Z] 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:582)
[2021-03-12T12:33:35.033Z] 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:767)
[2021-03-12T12:33:35.033Z] 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:759)
[2021-03-12T12:33:35.033Z] 	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:426)
[2021-03-12T12:33:35.033Z] 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:326)
[2021-03-12T12:33:35.033Z] 	at org.springframework.cloud.function.context.AbstractSpringFunctionAdapterInitializer.initialize(AbstractSpringFunctionAdapterInitializer.java:118)
[2021-03-12T12:33:35.033Z] 	at org.springframework.cloud.function.adapter.azure.AzureSpringBootRequestHandler.handleRequest(AzureSpringBootRequestHandler.java:82)
[2021-03-12T12:33:35.033Z] 	... 17 more
[2021-03-12T12:33:35.033Z] Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [io.r2dbc.pool.ConnectionPool]: Factory method 'connectionFactory' threw exception; nested exception is org.springframework.boot.autoconfigure.r2dbc.ConnectionFactoryBuilder$ConnectionFactoryBeanCreationException: Failed to determine a suitable R2DBC Connection URL
[2021-03-12T12:33:35.033Z] 	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
[2021-03-12T12:33:35.033Z] 	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653)
[2021-03-12T12:33:35.033Z] 	... 35 more
[2021-03-12T12:33:35.033Z] Caused by: org.springframework.boot.autoconfigure.r2dbc.ConnectionFactoryBuilder$ConnectionFactoryBeanCreationException: Failed to determine a suitable R2DBC Connection URL
[2021-03-12T12:33:35.033Z] 	at org.springframework.boot.autoconfigure.r2dbc.ConnectionFactoryBuilder$ConnectionFactoryOptionsInitializer.connectionFactoryBeanCreationException(ConnectionFactoryBuilder.java:227)
[2021-03-12T12:33:35.033Z] 	at org.springframework.boot.autoconfigure.r2dbc.ConnectionFactoryBuilder$ConnectionFactoryOptionsInitializer.initializeOptions(ConnectionFactoryBuilder.java:156)
[2021-03-12T12:33:35.033Z] 	at org.springframework.boot.autoconfigure.r2dbc.ConnectionFactoryBuilder.of(ConnectionFactoryBuilder.java:62)
[2021-03-12T12:33:35.033Z] 	at org.springframework.boot.autoconfigure.r2dbc.ConnectionFactoryConfigurations.createConnectionFactory(ConnectionFactoryConfigurations.java:53)
[2021-03-12T12:33:35.033Z] 	at org.springframework.boot.autoconfigure.r2dbc.ConnectionFactoryConfigurations$Pool.connectionFactory(ConnectionFactoryConfigurations.java:70)
[2021-03-12T12:33:35.033Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2021-03-12T12:33:35.033Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2021-03-12T12:33:35.033Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2021-03-12T12:33:35.033Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2021-03-12T12:33:35.033Z] 	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
[2021-03-12T12:33:35.033Z] 	... 36 more
[2021-03-12T12:33:35.033Z] .
```

I have R2DBC autoconfiguration disabled as I created my own Configuration which looks like this:
```
@Configuration
public class DatabaseConfiguration extends AbstractR2dbcConfiguration {

    private final Logger log = LoggerFactory.getLogger(DatabaseConfiguration.class);

    @Override
    @Bean
    public ConnectionFactory connectionFactory() {
        log.info("Connecting to database...");

        return new MssqlConnectionFactory(MssqlConnectionConfiguration.builder()
                .host("...")
                .port(1433)
                .database("...")
                .username("...")
                .password("...")
                .build());
    }
}
```

**Comment by jdubois** [comment]
This code is about 2 years old, have you had a look at the current documentation at:
https://docs.microsoft.com/azure/developer/java/spring-framework/configure-spring-data-r2dbc-with-azure-sql-server

Also, I'm using the auto-configuration, so if you replace it with your own configuration, I can't guarantee it will work.

**Comment by itsandreramon** [comment]
I tried this tutorial as well, it works as expected when deployed normally but fails as a function deployment

**Comment by jdubois** [comment]
OK, so you get the R2DBC connection working, and you have an issue with the function deployment.
For deploying a function, I've got this other tutorial, which is up-to-date, can you try it: https://github.com/Azure-Samples/hello-spring-function-azure

**Comment by itsandreramon** [comment]
I looked at all of them, but as far as I can tell they are either using Azure SQL R2DBC without Functions, or using Azure Functions without R2DBC.

**Comment by jdubois** [comment]
Indeed, I didn't do one with this specific combination. We'll soon publish a MS Learn module with Functions and Cosmos DB - not the same backend, but it should be closer.
Anyway, there shouldn't be a specific configuration for Function + R2DBC, connecting to your database should be the same as with App Service + R2DBC.
What's your specific error? Do you have stacktrace or some message?
